### ISSUE TITLE
Перестали работать голосовые команды

### ISSUE THREAD

**Issue by TuTAH1** [Mikolaytis/LaitisIntegration#10]
Они распознаются, но ничего не происходит. В журнале отображается это:
![image](https://user-images.githubusercontent.com/15982179/151356451-6b9e58ae-75ff-4d63-b56e-b5eb8b3840e1.png)
И как сделать бекап команд, где они находятся?

**Comment by mklts** [comment]
бекапы в c/users/{user}/appdata/local/laitis/backups
загрузить бекап можно из настроек

**Comment by mklts** [comment]
узнайте, упало ли прям у всех (в группе вк). Если так - то пусть напишут мне в телегу

**Comment by TuTAH1** [comment]
Вчера само собой починилось
