### ISSUE TITLE
Редактировать команды как текст

### ISSUE THREAD

**Issue by TuTAH1** [Mikolaytis/LaitisIntegration#11]
Можно ли это делать? Если нет, то добавьте такую возможность (делать команды с помощью псевдокода) – блочное программирование (особенно, в такой реализации, какая она есть сейчас) очень неудобно

**Comment by mklts** [comment]
как есть... добавлять возможность писать скрипты нельзя в мс стор. запрещено правилами. поэтому даже нет мыслей такое делать.

**Comment by TuTAH1** [comment]
>добавлять возможность писать скрипты нельзя в мс стор. запрещено правилами. поэтому даже нет мыслей такое делать.

Дык по сути, у программы же уже есть возможность писать скрипты, только не через текст, а через блоки. Может эти команды куда-нибудь сохраняются, что их можно отредактировать как текст? Ну или, сделать так, чтобы сохранялись – по сути вы же тогда возможность писать скрипты не дадите, а то что пользователи редактируют файлы вашей программы – это уже не ваши проблемы :)

**Comment by mklts** [comment]
парсите json настроек, и редактируйте вручную appdata/local/laitis/save.json
