### ISSUE TITLE
Laitis is not connected

### ISSUE THREAD

**Issue by whoim2** [Mikolaytis/LaitisIntegration#13]
Домовенок кузя. Программа на компе открыта, сработало "компьютер в спящий режим" один раз. Разбудил, больше не хочет, в логах кузи:
`Ответ на правило компьютер спящий режим
2022-07-13 20:29:43.981000
Расширенный HTTP 
Анализ URL: https://laitis.ru/send?key=агащас&phrase=перейти в спящий режим
Запрашиваемый URL: https://laitis.ru/send?key=агасчас&phrase=%D0%BF%D0%B5%D1%80%D0%B5%D0%B9%D1%82%D0%B8+%D0%B2+%D1%81%D0%BF%D1%8F%D1%89%D0%B8%D0%B9+%D1%80%D0%B5%D0%B6%D0%B8%D0%BC
Не проверяем сертификат SSL
GET /send?key=агасчас&phrase=%D0%BF%D0%B5%D1%80%D0%B5%D0%B9%D1%82%D0%B8+%D0%B2+%D1%81%D0%BF%D1%8F%D1%89%D0%B8%D0%B9+%D1%80%D0%B5%D0%B6%D0%B8%D0%BC HTTP/1.1
Host: laitis.ru
Accept: */*

Код ответа: 200
Заголовок ответа:
HTTP/1.1 200 OK
Cache-Control: private,public
Content-Type: text/html; charset=utf-8
Server: Microsoft-IIS/8.5
X-AspNetMvc-Version: 5.2
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Date: Wed, 13 Jul 2022 20:29:43 GMT
Content-Length: 23

Ошибка разбора JSON: 4
результат кладем в {"body":результат}Ответ сервера:
Laitis is not connected
2022-07-13 20:29:44.052500
Время работы скрипта(сек): 0.071512937545776`

**Comment by salvador9721** [comment]
Та же хрень. Временно решил перезапуском Laitisa через BATник по факту выхода ПК из режима сна + каждые 4 часа.
