### ISSUE TITLE
[Question] Синтаксис фраз

### ISSUE THREAD

**Issue by TuTAH1** [Mikolaytis/LaitisIntegration#9]
Где можно найти синтаксис фраз? Например, использование слешей, скобок, кавычек и тд?

**Comment by mklts** [comment]
в вики этого репозитория и в подсказках внутри редактора команд программы Laitis

**Comment by TuTAH1** [comment]
> в вики этого репозитория и в подсказках внутри редактора команд программы Laitis

Я читал полностью и раздел "Помощь" в программе Laitis, и Wiki, но я там этого не нашёл. Если это там и вправду есть, не могли бы вы мне дать точечную ссылку?

По другим командам я узнал только, что можно поставить `/`, чтобы использовать несколько вариантов слов в одной команде. Но что делать, если я хочу объединить слешем не слова, а сочетания слов? А если я хочу добавить опциональное слово?

Post Scriptum. Наверное, вы не правильно поняли мой вопрос, из-за того, что я использовал не те слова. Я поправил название темы и описание

**Comment by mklts** [comment]
кроме слешей ничего больше нет. и не просили.

**Comment by TuTAH1** [comment]
> кроме слешей ничего больше нет. и не просили.

А как распространить слеш на всю фразу? Например, `Выполнить (Некоторая фраза)/(одно слово) {число} раз` (то есть, фраза должна срабатывать и с вариантом "Некоторая фраза" и с вариантом "одно слово". Заключение нескольких слов в скобки не работает как мне бы хотелось. Вот тогда список **предложений** к синтаксису фраз:

- `~слово` - опциональное слово/фраза, позволяет разбить фразу на две, одну, где это слово используется, вторую – где не.
- `(слова)` - скобки позволяют применять действия не к одному слову, а ко всему, что находится внутри скобок
- `"слово"` - запрет на изменение формы слова
